# AGS
bind = SUPER, D, exec, ags -b hypr toggle-window applauncher
bind = CTRL SHIFT, R, exec, ags -b hypr quit ; ags -b hypr

bindle = , XF86MonBrightnessUp,     exec, ags -b hypr -r "brightness.screen += 0.05; indicator.display()"
bindle = , XF86MonBrightnessDown,   exec, ags -b hypr -r "brightness.screen -= 0.05; indicator.display()"
bindl  = , XF86AudioMute,           exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindle = , XF86AudioRaiseVolume,    exec, ags -b hypr -r "audio.speaker.volume += 0.05; ags.Service.Indicator.speaker()"
bindle = , XF86AudioLowerVolume,    exec, ags -b hypr -r "audio.speaker.volume -= 0.05; ags.Service.Indicator.speaker()"
bindl  = , XF86AudioPlay,           exec, ags -b hypr -r "mpris()?.playPause()"
bindl  = , XF86AudioStop,           exec, ags -b hypr -r "mpris()?.stop()"
bindl  = , XF86AudioPause,          exec, ags -b hypr -r "mpris()?.pause()"
bindl  = , XF86AudioPrev,           exec, ags -b hypr -r "mpris()?.previous()"
bindl  = , XF86AudioNext,           exec, ags -b hypr -r "mpris()?.next()"

# SCREENSHOT/RECORD
bind = ,Print,                      exec, ags -b hypr run-js "recorder.screenshot()"
bind = SHIFT,Print,                 exec, ags -b hypr run-js "recorder.screenshot(true)"
bind = CTRL SHIFT,Print,           exec, ags -b hypr run-js "recorder.start()"

# APPS
bind = SUPER, Return, exec, wezterm
bind = SUPER, E, exec, nautilus -w

# WINDOW MANAGMENT
bind = SUPER, Q, killactive,
bind = SUPER, F, fullscreen,
bind = SUPER, Space, togglefloating,
bind = SUPER, P, pseudo,
bind = SUPER, S, togglesplit,
# Move windows
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d
# Resize windows
bind = SUPER CTRL, left, resizeactive, -20 0
bind = SUPER CTRL, right, resizeactive, 20 0
bind = SUPER CTRL, up, resizeactive, 0 -20
bind = SUPER CTRL, down, resizeactive, 0 20

# WORKSPACES
bind = SUPER, F1, workspace, 1
bind = SUPER, F2, workspace, 2
bind = SUPER, F3, workspace, 3
bind = SUPER, F4, workspace, 4
bind = SUPER, F5, workspace, 5
bind = SUPER, F6, workspace, 6
bind = SUPER, F7, workspace, 7

# MOUSE BINDS
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1
