windowrule = float, ^(Rofi)$
windowrule = float, ^(org.gnome.Calculator)$
windowrule = float, ^(org.gnome.Nautilus)$
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(nm-connection-editor)$
windowrule = float, ^(blueberry.py)$
windowrule = float, ^(org.gnome.Settings)$
windowrule = float, ^(org.gnome.design.Palette)$
windowrule = float, ^(Color Picker)$
windowrule = float, ^(Network)$
windowrule = float, ^(xdg-desktop-portal)$
windowrule = float, ^(xdg-desktop-portal-gnome)$
windowrule = float, ^(transmission-gtk)$
windowrule = float, ^(org.wezfurlong.wezterm)$
windowrule = float, ^(ags)$
windowrule = opacity 0.8 override 0.8 override,^(org.wezfurlong.wezterm)$

layerrule = blur, ^(bar0)$
layerrule = ignorealpha 0.4, ^(bar0)$
layerrule = blur, quicksettings
layerrule = ignorealpha 0.6, quicksettings
layerrule = blur, dashboard
layerrule = ignorealpha 0.4, dashboard
