general {
  layout = dwindle
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = true
  enable_swallow = true
}

input {
  kb_layout = cz
  follow_mouse = 1
  sensitivity = 0
}

dwindle {
  no_gaps_when_only = false
  pseudotile = true
  preserve_split = true
}

# master not included yet
master {
  new_is_master = false
}

gestures {
  workspace_swipe = on
}
