general {
  gaps_in = 8
  gaps_out = 16
  border_size = 0
}

decoration {
  rounding = 11
  
  active_opacity = 0.99
  inactive_opacity = 0.83

  drop_shadow = yes
  shadow_range = 8
  shadow_render_power = 2
  col.shadow = rgba(00000044)

  dim_inactive = false

  blur {
    enabled = true
    size = 1.5
    passes = 1
    new_optimizations = on
    noise = 0.01
    contrast = 0.9
    brightness = 0.8
  }
}

animations {
  enabled = yes
  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  animation = windows, 1, 5, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}
